Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 25
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 673
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 712
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 713
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 714
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 1441
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 1586
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 1956
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 1969
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 2209
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 2212
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 2214
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 2215
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 2260
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 2263
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 2321
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 2324
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 3791
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 3815
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 4843
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 4914
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 5156
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 5159
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 5228
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 5600
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 5894
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 7010
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 7422
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_coad 7423
