Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 2
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 291
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 292
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 293
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 316
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 596
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 712
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 713
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 714
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 836
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 842
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 1441
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 1588
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 1956
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 2064
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 2099
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 2100
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 2209
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 2212
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 2214
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 2475
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 2798
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 3359
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 3725
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 3973
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 4137
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 4842
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 4843
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 4846
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 5241
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 5321
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 5564
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 5578
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 5599
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 5742
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 5743
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 7018
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 7277
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 7422
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 7846
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 8600
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 8644
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_brca 10928
