Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 2
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 596
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 673
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 1493
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 1586
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 1588
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 2057
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 2099
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 2100
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 3350
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 3351
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 3359
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 3360
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 3454
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 3455
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 3725
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 3984
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 4137
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 4843
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 4988
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 5133
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 5228
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 5535
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 5578
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 5599
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 5604
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 5605
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 5743
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 5894
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 7018
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 7277
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 7422
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 7423
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 7846
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 10105
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 10928
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_skcm 150094
