Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 25
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 596
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 598
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 673
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 712
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 713
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 714
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 775
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 776
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 778
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 779
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 782
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 783
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 784
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 785
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 1436
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 1585
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 1588
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 1956
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 2064
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 2066
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 2099
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 2100
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 2185
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 2209
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 2212
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 2214
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 2260
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 2263
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 2321
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 2324
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 3725
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 3791
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 3815
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 4170
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 4790
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 4914
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 5133
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 5156
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 5159
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 5170
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 5578
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 5599
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 5742
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 5743
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 5894
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 7124
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 7277
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 7422
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 7846
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 8911
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 8912
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 8913
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/05_kstest_pvadj_logfc_kovsctrl/05_2_kstest_pvadj_logfc_kovsctrl.R tcga_lgg 10928
