Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 2
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 596
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 712
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 713
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 714
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 1441
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 1588
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 1956
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 2209
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 2212
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 2214
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 3065
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 3725
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 4036
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 4137
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 5133
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 5742
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 5743
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 7018
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 7422
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 7846
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_luad 8600
