Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 2
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 316
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 476
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 596
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 712
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 713
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 714
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 1438
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 1439
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 1586
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 1588
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 1956
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 2209
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 2212
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 2214
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 2215
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 3563
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 4137
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 4842
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 4843
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 4846
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 5321
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 5742
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 5743
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 7018
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 7277
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 8644
Rscript /mnt/lustre/scratch/CBRA/research/projects/tcga_mm/code/04_mm_ko_drug_used/04_3_pathvals_ko_drug_used/04_3_pathvals_ko_drug_used.R tcga_stad 10928
